name: Build Paper

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Upload Paper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: src
          latexmk_shell_escape: true
          extra_system_packages: 'py-pygments'
      - uses: actions/upload-artifact@v2
        with:
          name: paper
          path: src/main.pdf
  gh-pages:
    name: Publish pdf on gh-pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: paper
          path: paper
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: paper
